# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-04 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='responsitory.TagInfo', verbose_name='标签'),
        ),
    ]
