# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-04 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0002_articleinfo_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Article2Tag',
        ),
    ]
