# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-05 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0003_auto_20181004_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluateinfo',
            name='action',
            field=models.IntegerField(choices=[(1, '赞'), (-1, '踩')], verbose_name='动作'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluateinfo',
            unique_together=set([('article', 'user')]),
        ),
    ]
